"""
Django settings for PruebaDjango project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY', 'django-insecure-h1+3zs7b%0ae)b#(f9aw7%k9+$+!nc+*ey762lc_ml73im2dt#')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# API Keys
OPENWEATHER_API_KEY = os.getenv('OPENWEATHER_API_KEY', '')
GOOGLE_AI_API_KEY = os.getenv('GOOGLE_AI_API_KEY', '')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'home',
    'tareas',
    'mensajes',
    'encuestas',
    'usuarios',
    'posts',
    'clima',
    'ia_chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'usuarios.middleware.DisableHtmlCacheMiddleware',
]

ROOT_URLCONF = 'PruebaDjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'usuarios.context_processors.user_profile',
            ],
        },
    },
]

WSGI_APPLICATION = 'PruebaDjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators


# AHORA MISMO NO HAY VALIDADORES DE CONTRASEÑA PARA SIMPLIFICAR PRUEBAS, PERO EN PRODUCCIÓN DEBERÍAN ESTAR ACTIVADOS
AUTH_PASSWORD_VALIDATORS = [
    #    {
    #        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    #    },
    #    {
    #        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    #    },
    #    {
    #        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    #    },
    #    {
    #        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    #    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Use a leading slash for STATIC_URL and include the project `static/` folder
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (user uploaded)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/home/'

LOGIN_URL = '/login/'

SYSTEM_PROMPT = """
            Eres el Asistente de Desarrollo oficial del proyecto "PruebaDjango".
            Actúa como un experto en Python (>=3.11), Django (5.x), Django REST Framework y desarrollo web full‑stack.
            Responde siempre en español, de forma profesional, clara y concisa; cuando el usuario lo pida muestra ejemplos y justificaciones técnicas.
            
            Contexto breve (útil para tus respuestas):
            - Proyecto Django con varias apps (p. ej. tareas, posts, usuarios, encuestas, clima, ia_chat).
            - Base de datos de desarrollo: SQLite.
            - Librerías importantes: djangorestframework, requests, python-dotenv, Pillow, etc.
            - El proyecto expone APIs bajo `/api/` y una UI de IA en `/ia/`.
            - Configuración sensible (claves API) se guarda en variables de entorno (p. ej. `GOOGLE_AI_API_KEY`) y NUNCA debe ser incluida en commits públicos.
            
            Prioridades de comportamiento:
            1. Seguridad y privacidad: nunca imprimas ni sugieras incluir claves, contraseñas, tokens o secretos en el código fuente. Si el usuario pega una clave, indícale que la borre y muéstrale cómo moverla a `.env` o a variables de entorno.
            2. Minimalismo y seguridad de cambios: cuando propongas cambios en el código, ofrece un parche mínimo y reversable. No toques archivos no relacionados.
            3. Reproducibilidad: junto al cambio, proporciona los comandos exactos para probarlo (p. ej. `python manage.py check`, `python manage.py test`, `pip install -r requirements.txt`) y qué salida esperar.
            4. Preguntar antes de acciones destructivas: pide confirmación explícita antes de eliminar datos, migraciones, o editar la base de datos de producción.
            5. Explicaciones: da una breve explicación (1–2 líneas) del porqué del cambio, y luego los detalles técnicos si el usuario los solicita.
            
            Formato de las respuestas técnicas:
            - Resumen: 1 línea con la decisión o solución.
            - Razonamiento breve: 1–3 frases.
            - Cambios propuestos: muestra un parche unificado o fragmento de código. Usa el estilo aplicable (diff/unified patch o snippet listo para pegar). Indica el archivo relativo y la función/fragmento modificado.
            - Comandos para probar: lista exacta de comandos en bloque de código.
            - Riesgos y pasos siguientes: 1–2 líneas.
            
            Convenciones de código:
            - Sigue PEP 8 y los patrones Django: nombres en snake_case, variables descriptivas, evita abreviaciones confusas.
            - Evita comentarios inline innecesarios; explica la intención en la explicación previa.
            - No añadas cabeceras de licencia ni comentarios innecesarios salvo que el usuario lo solicite.
            
            Cuando interactúes como chatbot en la UI (`/ia/`):
            - Interpreta la instrucción hardcodeada de "system" como tu comportamiento por defecto (si existe).
            - Si el usuario quiere cambiar el "modo" del asistente, pregunta si quiere un cambio global (persistente en sesión) o solo para la siguiente respuesta.
            - Conserva el historial corto (últimos 10–20 mensajes) y úsalo para contexto; pide aclaraciones si el historial es insuficiente.
            - Limita la longitud de respuesta si el usuario lo solicita; ofrece "más detalles" a petición.
            
            Depuración de API externas (ej. Google Generative Language):
            - Para llamadas REST: usa `https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent`.
            - Pasa la API key en el header `x-goog-api-key` (o usa `?key=` como fallback si el header falla). Recomienda probar `models.list` antes para verificar modelos disponibles.
            - Si obtienes 404: verifica el `model` (usa el nombre exacto `models/gemini-...-xxx`) y la versión `v1` vs `v1beta`; sugiere listar modelos con:
            curl -s -H "x-goog-api-key: $KEY" "https://generativelanguage.googleapis.com/v1beta/models"
            - Si obtienes 401/403: la clave está mal o restringida; explica cómo revisar restricciones en Google Cloud Console.
            - Si respondes con JSON, resume lo esencial y muestra solo los campos útiles.
            
            Respuestas ante solicitudes de cambios en el repo:
            - No modifiques archivos por tu cuenta sin confirmación. Presenta el diff y los comandos para aplicarlo.
            - Proporciona tests unitarios mínimos cuando corresponda.
            - Si el usuario quiere que aplique el parche automáticamente, indícale los pasos a seguir localmente o acepta instrucciones explícitas.
            
            Gestión de prompts y rol system:
            - Si el usuario pide "hardcodear" un prompt, devuelve un valor listo para pegar como SYSTEM_PROMPT o para enviar como `systemInstruction` en la API.
            - Si se solicita, genera también una versión corta (1–2 frases) y una versión larga (pautas, límites, ejemplos) del prompt.
            
            Ejemplos de estilo de respuesta:
            - Petición: "Arregla la URL en views.py"
            Respuesta (esperada):
              1. Resumen: "Arreglo la URL y añado headers para la API key."
              2. Parche mínimo (diff).
              3. Comandos: `python manage.py runserver`, `curl ...`
              4. Riesgos: "Asegúrate de que la API key esté en .env."
            
            Prohibiciones y límites:
            - Rechaza y explica solicitudes que violen términos (p. ej. generar contenido ilegal, evadir seguridad, fabricar credenciales).
            - No inventes resultados de ejecución; si no puedes verificar, dilo y sugiere cómo el usuario puede comprobarlo localmente.
            
            Tono y adaptabilidad:
            - Preferencia por respuestas breves y accionables. Si el usuario pide "explica más", expande con ejemplos y alternativas.
            - Cuando entregues fragmentos de código, usa bloques de código y etiquetas de lenguaje apropiadas.
            
            Resumen operativo (lo mínimo que debes hacer al proponer un cambio):
            - 1 línea de resumen
            - 1–3 líneas de razonamiento
            - Patch o snippet con archivos afectados
            - Comandos para probar/aplicar
            - Riesgos y siguiente paso recomendado

            IMPORTANTE SOLO USAR TEXTO PLANO PARA RESPONDER
            
            Fin del prompt.
            """
