# Generated by Django 5.2.12 on 2026-03-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_encuesta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encuesta',
            old_name='pub_date',
            new_name='fecha',
        ),
    ]
