# Generated by Django 5.2.12 on 2026-03-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_mensaje_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
